fix: and add response streaming feature(toggle off). Close #122
aws-samples/aws-genai-conversational-rag-reference pull request #134
Opened 2024-05-27 00:18 UTC by jessieweiyi

## Description
This PR includes @sperka PR #130. The PR has been tested on different use cases and fix a few issues. The PR also:
* Tested with langchain version 0.1.36 (Upgraded in PR #131) - The issue where only one chunk returned cannot be identified
* Allows users to config whether to stream response for Bedrock models

Issues found in the streaming feature, so add a feature flag on the feature to toggle it off: 
* When issue occurs, the button is loading forever 
* The second requests do not get the update

To toggle on: add ?features=streaming query string to the url 

Pending To-do items:
* With streaming, it should implement a progress bar in chat panel
* upgrade `lambda-powertools` to v2

Here is a copied of original PR description: 

This PR introduces streaming support and was also targeting a bit of a cleanup/refresh.

* vscode settings update (use vscode v1.85+) - editor settings had breaking changes
* adjust projenrc setup to conform [aws-pdk](https://github.com/aws/aws-pdk) update breaking changes
* bump dependencies to `latest` or `latest-that-doesn't-break-anything`
* replace discontinued @aws-sdk packages with @smithy packages
* fix for #112 
* tsconfig settings update for apis and website
* fix first-deployment issue for admin user/group dependency
* add [Websocket API](https://aws.github.io/aws-pdk/developer_guides/type-safe-api/websocket_getting_started.html) from PDK's `type-safe-api`
* add streaming support to RAG chain and split `create-message` handler to support `REST` and `WS`
* add websocket connection management (via ddb persistance)
* restructure infra nested stack setup to avoid circular dependencies
* website updated to support websocket connections

There are a few things that should be added or changed (refer to `// TODO`s in the code):

1. Website 
    * make choice of streaming/rest call configurable
    * with streaming, it should implement a progress bar in chat panel
2. SDK (RAG chain)
   * Currently `langchain@0.0.194` version is used, there were huge improvements so updating to latest should be inevitable - however, this includes quite a bit of effort
   * Also, `lambda-powertools` v2 is out, but has breaking changes
   * `qaChain` definition and how streaming is handled, especially based on the models used. With the current generic approach, streaming is not happening, there is only one chunk returned (which is the actual result) instead of incremental answer (aka tokens). This _may be_ an issue because of the langchain version, _or_ something else. That part needs to be tested, both for bedrock LLMs and Sagemaker-hosted LLMs.
3. Websocket communication structure
    * Current implementation is not as restrictive as it should be, `operation` value can be any string value which should be restricted to `enum`, and maybe other fields could be limited as well -- needs thorough review 
4. Add docs

**Does this PR introduce a breaking change?**  
No breaking change. The streaming feature is under a feature toggle. 

## Related Issues/Discussion

## How Has This Been Tested?

* **What environment was this tested on?**

## Screenshots (if appropriate)

## PR Checklist

* [ ] Have you added/updated documentation?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran build and tests with your changes locally?

**IMPORTANT:** Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

2024-05-27 01:23 UTC, martenpayne requested changes
couple minor comments

2024-05-27 01:23 UTC, martenpayne commented on demo/website/src/hooks/ws-chats.ts
> +        // const result = input.payload as CreateChatMessageResponseContent;
dead code?

2024-05-27 01:23 UTC, martenpayne commented on demo/infra/src/application/ai/inference-engine/engine/handler/ws-handler/index.ts
> +
dead whitespace

2024-05-27 01:23 UTC, martenpayne commented on demo/infra/src/application/presentation/index.ts
> +    // policy.attachToRole(props.authenticatedUserRole);
dead code

2024-05-27 01:23 UTC, martenpayne commented on packages/galileo-sdk/src/chat/callback.ts
> +export interface ChainOperationPayload {
minor: add newline

2024-05-27 01:23 UTC, martenpayne commented on packages/galileo-sdk/src/chat/engine.ts
> +
extraneous newline

2024-05-27 01:23 UTC, martenpayne commented on packages/galileo-sdk/src/chat/engine.ts
> +
extraneous newline?

2024-05-27 12:08 UTC, chn217 commented on demo/website/src/components/chat/components/HumanInputForm.tsx
>    }, [useStreaming, createChatMessage.isLoading]);
nit: the 2nd param of useEffect hook should include isStreamingResponse

2024-05-27 12:21 UTC, chn217 reviewed
Nice work on this PR! 👏

Just a general comment: I noticed that there are a few TODOs included in this PR. It would be good to track these TODOs in separate issues in the backlog to ensure they don't get lost or forgotten. 

The most important missing TODO seems to be related to documentation (DOC). We should create a separate issue for this and prioritize it accordingly.

2024-05-29 05:25 UTC, martenpayne approved these changes

2024-05-29 06:15 UTC, merged